"""Domain models, dataclasses, and immutable structures for the Vision Subsystem."""

import copy
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from types import MappingProxyType
from typing import Any, Dict, List, Optional, Tuple


@dataclass(frozen=True)
class ImageMetadata:
    """Metadata describing an image's dimensions, color mode, and file size."""
    width: int
    height: int
    format: str = "png"
    mode: str = "RGB"
    file_size_bytes: int = 0
    monitor_index: int = 0

    def __post_init__(self) -> None:
        if self.width <= 0 or self.height <= 0:
            raise ValueError("Image dimensions width and height must be positive.")
        if self.file_size_bytes < 0:
            raise ValueError("file_size_bytes must be non-negative.")

    @property
    def aspect_ratio(self) -> float:
        return round(self.width / self.height, 2)


@dataclass(frozen=True)
class VisionImage:
    """Structured representation of captured or loaded image data."""
    image_bytes: bytes
    metadata: ImageMetadata
    source: str = "fullscreen"  # 'fullscreen', 'active_window', 'region', 'clipboard', 'file'
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def __post_init__(self) -> None:
        if not self.image_bytes:
            raise ValueError("VisionImage image_bytes cannot be empty.")
        if self.timestamp.tzinfo is None or self.timestamp.tzinfo.utcoffset(self.timestamp) is None:
            raise ValueError("VisionImage timestamp must be timezone-aware.")


@dataclass(frozen=True)
class DetectedRegion:
    """Represents a bounded sub-region identified within an image."""
    x: int
    y: int
    width: int
    height: int
    label: str = ""
    confidence: float = 1.0

    def __post_init__(self) -> None:
        if self.x < 0 or self.y < 0:
            raise ValueError("Region coordinates x and y must be non-negative.")
        if self.width <= 0 or self.height <= 0:
            raise ValueError("Region dimensions width and height must be positive.")
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError("Region confidence must be between 0.0 and 1.0.")

    @property
    def bounding_box(self) -> Tuple[int, int, int, int]:
        return (self.x, self.y, self.width, self.height)


@dataclass(frozen=True)
class OCRResult:
    """Encapsulates text extracted by the local OCR engine."""
    text: str
    regions: List[DetectedRegion] = field(default_factory=list)
    confidence: float = 1.0
    language: str = "eng"

    def __post_init__(self) -> None:
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError("OCR confidence must be between 0.0 and 1.0.")
        copied_regions = list(self.regions)
        object.__setattr__(self, "regions", copied_regions)


@dataclass(frozen=True)
class Annotation:
    """Represents visual annotations placed over an image."""
    annotation_type: str  # 'bounding_box', 'highlight', 'text_label'
    region: DetectedRegion
    color: str = "#FF0000"
    label: str = ""


@dataclass(frozen=True)
class VisionRequest:
    """Encapsulates an incoming visual analysis request."""
    image: VisionImage
    prompt: str = "Describe what is shown in this image."
    request_id: str = field(default_factory=lambda: f"vreq_{uuid.uuid4().hex[:8]}")
    focus_region: Optional[DetectedRegion] = None
    enable_ocr: bool = True
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.prompt.strip():
            raise ValueError("VisionRequest prompt cannot be empty.")
        copied_metadata = copy.deepcopy(self.metadata)
        object.__setattr__(self, "metadata", MappingProxyType(copied_metadata))


@dataclass(frozen=True)
class VisionResponse:
    """Encapsulates the structured output generated by the Vision Runtime."""
    response_id: str
    request_id: str
    text: str
    ocr_result: Optional[OCRResult] = None
    detected_regions: List[DetectedRegion] = field(default_factory=list)
    confidence: float = 1.0
    duration_seconds: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.duration_seconds < 0.0:
            raise ValueError("duration_seconds must be non-negative.")
        copied_regions = list(self.detected_regions)
        object.__setattr__(self, "detected_regions", copied_regions)
        copied_metadata = copy.deepcopy(self.metadata)
        object.__setattr__(self, "metadata", MappingProxyType(copied_metadata))
