"""Data models for Agent requests, responses, and tool calls."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Any


@dataclass(frozen=True)
class ToolCall:
    """Represents a tool execution request generated by the AI model.

    Attributes:
        tool_name: The name of the tool to execute.
        arguments: Arguments dictionary to pass to the tool.
        requires_confirmation: Whether execution requires user approval.
    """

    tool_name: str
    arguments: Dict[str, Any]
    requires_confirmation: bool = False


@dataclass(frozen=True)
class AgentRequest:
    """Represents an incoming prompt or command for the agent.

    Attributes:
        request_id: Unique identifier for the request.
        text: The text content of the user input.
        source: The originating source (e.g., 'ui', 'voice').
        timestamp: Time the request was received.
        metadata: Optional metadata.
    """

    request_id: str
    text: str
    source: str
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgentResponse:
    """Represents the output from the agent orchestration loop.

    Attributes:
        response_id: Unique identifier for the response.
        text: The final text response generated for the user.
        tool_calls: List of tool execution requests identified in the loop.
        success: Whether the request was successfully processed.
        metadata: Optional metadata.
    """

    response_id: str
    text: str
    tool_calls: List[ToolCall] = field(default_factory=list)
    success: bool = True
    metadata: Dict[str, Any] = field(default_factory=dict)
